name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: "^4.0.0+2"
  angular_forms: "^1.0.0"
  firebase: "^4.3.1"

dev_dependencies:
  angular_test: "^1.0.1"
  browser: "^0.10.0+2"
  dart_to_js_script_rewriter: "^1.0.3"
  test: "^0.12.30+1"

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
